-- Llamadas a procedimientos sin parámetros
CALL SELECT_DEPARTAMENTO_RECORD();
CALL SELECT_PUESTO_RECORD();
CALL SELECT_EMPLEADO_RECORD();


-- Llamadas a procedimientos con parámetros (reemplaza el valor según corresponda)
CALL SELECT_PROVEEDORSERVICIOS_RECORD(1);
CALL SELECT_SERVICIOSPROVEIDOS_RECORD(1);
CALL SELECT_EVALUACIONDESEMPENO_RECORD(1);
CALL SELECT_PARIENTE_RECORD(1);
CALL SELECT_ANTICIPO_RECORD(1);
CALL SELECT_PERMISO_RECORD(1);
CALL SELECT_SEGUROMEDICO_RECORD(1);
CALL SELECT_RENDICIONCUENTAS_RECORD(1);
CALL SELECT_INCIDENCIAS_RECORD(1);
CALL SELECT_CAPACITACIONES_RECORD(1);
CALL SELECT_EVALUACIONCAPACITACIONES_RECORD(1);
CALL SELECT_PROYECTOS_RECORD(1);
CALL SELECT_ASIGNACIONESPROYECTO_RECORD(1);
CALL SELECT_EVALUACIONESPROYECTOS_RECORD(1);
CALL SELECT_DEPENDIENTES_RECORD(1);
CALL SELECT_PLANCARRERA_RECORD(1);
CALL SELECT_DOCUMENTOS_RECORD(1);
CALL SELECT_NOMINA_RECORD(1);
CALL SELECT_BONIFICACION_RECORD(1);
CALL SELECT_DESCUENTO_RECORD(1);
CALL SELECT_VACACIONES_RECORD(1);
CALL SELECT_HORARIOS_RECORD(1);
CALL SELECT_ASISTENCIA_RECORD(1);
CALL SELECT_COMISIONES_RECORD(1);
CALL SELECT_ANTIGUEDAD_RECORD(1);
CALL SELECT_HISTORIALSALARIOS_RECORD(1);
CALL SELECT_ESTADOPATRIMONIAL_RECORD(1);
